#version: "3.4"

services:
    sisponto:
        container_name: sisponto-laravel
        tty: true
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ./:/var/www
#            - ./../xdebug.ini:/etc/php82/conf.d/50_xdebug.ini
        #entrypoint: "/bin/sh"
        #entrypoint: ["composer", "install"]
#        entrypoint: ["composer", "start"]
        #entrypoint: [ "php", "artisan", "serve" ]
        #entrypoint: [ "php", "-S", "0.0.0.0:8000" ]
        ports:
            - "8000:8000"

    sisponto-db:
        image: mysql:5.7
        container_name: sisponto-db
#        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sisponto
        ports:
            - 3306:3306
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 9001:80
        networks:
            - app-network
        environment:
            - PMA_ARBITRARY=1

networks:
    app-network:
volumes:
    db_data:
#    sisponto-db:
#        driver: local
