name: Code Review

on:
  push:
    branches:
      - 'main'

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Review Code by IA
        uses: fitomad/github-chatgpt-integration@main
        with:
          github-token: ${{ secrets.TOKEN_GITHUB }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          github_pr_id: ${{ github.event.number }}
          openai_model: "gpt-3.5-turbo" # optional
          openai_temperature: 0.5 # optional
          openai_max_tokens: 2048 # optional
          mode: file # files or patch
          language: pt-br # optional, default is 'en'
          custom_prompt: "" # optional
